### ISSUE TITLE
Problems with ios

### ISSUE THREAD

**Issue by reaperspeeds** [Tw1ddle/samcodes-notifications#1]
Hi, I am using this extension to make notifications in our games, in android work well!, but in ios have the next error:
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make
Haxe device build: Release-iphoneos-v7
haxe Build.hxml -D HXCPP_ARMV7 -cpp build/Release-iphoneos-v7 
/usr/local/lib/haxe/lib/samcodes-notifications/1,0,1/extension/notifications/Notifications.hx:36: characters 2-35 : Not enough arguments
/usr/local/lib/haxe/lib/samcodes-notifications/1,0,1/extension/notifications/Notifications.hx:44: characters 9-49 : Not enough arguments
/usr/local/lib/haxe/lib/samcodes-notifications/1,0,1/extension/notifications/Notifications.hx:40: lines 40-46 : Missing return Int
make: *** [build-haxe-armv7] Error 1

** BUILD FAILED **

````
Thanks in advance for your help

**Comment by Tw1ddle** [comment]
Hey, I will look into this this weekend. I have a couple of ideas:

Does downgrading to hxcpp version 3.2.205 stop the problem from coming up? 
Does updating to the latest haxelib help? Read the changelog if it does, there's a breaking change, so you'll need to specify notification delays in seconds.

**Comment by Tw1ddle** [comment]
@reaperspeeds I've been busier than expected but will check this again when I find time. Did either of the suggestions above fix it?

**Comment by reaperspeeds** [comment]
Hi @Tw1ddle  I tried to install hxcpp 3.2.205 and i have the same issue...
I'm sorry I could barely try it today

**Comment by Tw1ddle** [comment]
Hey @reaperspeeds I finally had a chance to do some builds (with hxcpp 3.2.205) on iOS with version 1.0.5 of the haxelib, and did not encounter this problem.

Maybe the issue was a problem with my 1.0.1 release, that has been fixed since?

**Comment by Tw1ddle** [comment]
I can't reproduce the issue with the 1.0.5 release.

If it's still a problem then let me know if it happens on the latest version, plus list the haxelib versions you're using and iOS build settings, and I'll try to reproduce it. Thanks!
