### ISSUE TITLE
Ability to set icons

### ISSUE THREAD

**Issue by JoeCreates** [Tw1ddle/samcodes-notifications#2]
Could we get the ability to set the icons and not just have the app icon with the info badge? Thanks!

**Comment by Tw1ddle** [comment]
I can think of a few ways to do this on Android:

Most flexible would be to be able to send image data from Haxe to Android, and then save that to be displayed later.

But a simpler way is to associate notification slot ids with optional icons i.e. _slot 0 -> res.slot_0_samcodes_notification_icon, slot 1 -> res.slot_1_samcodes_notification_icon_ etc. Probably stored as Android resources, which we can try to fetch programmatically using the _Resources.getIdentifier_ method.

On iOS it looks annoying to display custom images inline with notification alerts, assuming this is the only way. Probably not worth the effort: https://developer.apple.com/documentation/usernotificationsui/unnotificationcontentextension
Some discussion: https://stackoverflow.com/questions/39063942/image-from-attachment-from-local-notification-is-not-shown-in-unnotificationcont

**Comment by Tw1ddle** [comment]
Done this for Android now - we can specify names for the small/large notification icon files to show with each notification. This also preserves the old behavior by using the application icon or generic icon as a fallback if no icon names are specified.

I've implemented an example of this in the demo app: https://github.com/Tw1ddle/samcodes-notifications-demo

In the demo, the icons are copied to the Android res/drawable folder of the app via Project.xml like so:

> \<assets path="assets/icons" rename="app/src/main/res/drawable" type="template" /\>

We could do something similar for iOS, but am going to leave that alone that for now.
