### ISSUE TITLE
Avoid dependencies

### ISSUE THREAD

**Issue by smival** [Tw1ddle/samcodes-notifications#3]
is it possible to assemble this lib without dependencies (android-support-v4.jar)?

**Comment by smival** [comment]
I mean my specific project has extension-android-support-v4 and it throws "multiple dex files define" error.
following lines I tried to add:

for haxelib.json
```
"dependencies": {
		"extension-android-support-v4": ""
	}
```

for include.xml

```
...
<section if="android">
		<haxelib name="extension-android-support-v4" if="openfl-next || openfl-legacy" />
...
```

also samcodes-notifications\1,0,5\dependencies\samcodes-notifications\libs folder has been removed

but the error still here:

 BootReceiver.java:14: error: package android.support.v4.app does not exist
import android.support.v4.app.NotificationCompat;
                             ^
 BootReceiver.java:15: error: package android.support.v4.app.NotificationCompat does not exist
import android.support.v4.app.NotificationCompat.Builder;
                                                ^
 PresenterReceiver.java:18: error: package android.support.v4.app does not exist
import android.support.v4.app.NotificationCompat;
                             ^
 PresenterReceiver.java:19: error: package android.support.v4.app.NotificationCompat does not exist
import android.support.v4.app.NotificationCompat.Builder;
                                                ^
 PresenterReceiver.java:123: error: package NotificationCompat does not exist
                NotificationCompat.Builder builder = new NotificationCompat.Builder(applicationContext);
                                  ^
 PresenterReceiver.java:123: error: package NotificationCompat does not exist
                NotificationCompat.Builder builder = new NotificationCompat.Builder(applicationContext);
                                                                           ^
 PresenterReceiver.java:136: error: cannot find symbol
                builder.setDefaults(NotificationCompat.DEFAULT_SOUND | NotificationCompat.DEFAULT_VIBRATE | NotificationCompat.DEFAULT_LIGHTS);
                                    ^
  symbol:   variable NotificationCompat
  location: class PresenterReceiver
 PresenterReceiver.java:136: error: cannot find symbol
                builder.setDefaults(NotificationCompat.DEFAULT_SOUND | NotificationCompat.DEFAULT_VIBRATE | NotificationCompat.DEFAULT_LIGHTS);
                                                                       ^
  symbol:   variable NotificationCompat
  location: class PresenterReceiver
 PresenterReceiver.java:136: error: cannot find symbol
                builder.setDefaults(NotificationCompat.DEFAULT_SOUND | NotificationCompat.DEFAULT_VIBRATE | NotificationCompat.DEFAULT_LIGHTS);
                                                                                                            ^
  symbol:   variable NotificationCompat
  location: class PresenterReceiver

**Comment by Tw1ddle** [comment]
Hi @smival I'm not sure why it's not working after the changes you mentioned. Perhaps you also need to add this line to project.properties?

`android.library.reference.2=../android-support-v4`

I will update the haxelib to use the extension-android-support-v4 extension when possible to fix the dexing error, looks like you're on the right track.

**Comment by smival** [comment]
hi @Tw1ddle , thanks for your suggestion, I add this line to dependencies\samcodes-notifications\project.properties
and it changes nothing , hmm.
looks like we use different JAR files (this lib and extension-android-support-v4)

**Comment by smival** [comment]
so looks like I solve this issue, just copy gradle build file from extension-facebook, for example.
```
buildscript {
    repositories {
        maven {
            url "http://repo1.maven.org/maven2/"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
    }
}

apply plugin: 'com.android.library'

android {
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
        }
    }
    compileSdkVersion Integer.parseInt(project.ANDROID_BUILD_SDK_VERSION)
    buildToolsVersion project.ANDROID_BUILD_TOOLS_VERSION
}

dependencies {	
    compile project(':deps:extension-api')
    compile 'com.android.support:support-v4:[23,24)'
}
```

**Comment by Tw1ddle** [comment]
I see, I guess you were using a recent version of OpenFL that uses gradle instead of ant for building. Haven't tried that yet, on my list of things to do.
