### ISSUE TITLE
is It possible to remove app permissions?

### ISSUE THREAD

**Issue by Tembac** [Tw1ddle/samcodes-notifications#7]
After I added this extension to my game now it is asking for permissions of Phone and Storage. I don't see that this is really needed by the extension but I can't find how to remove them.

**Comment by Tw1ddle** [comment]
Hi, it depends on what the exact phone/storage permissions are. Some permissions are needed to set badges on the app icons works on all brands of phone. This is the relevant place:

https://github.com/Tw1ddle/samcodes-notifications/blob/master/dependencies/samcodes-notifications/AndroidManifest.xml

In fact, it probably needs updating based on these permissions that ShortcutBadger uses:

https://github.com/leolin310148/ShortcutBadger/blob/50d422d1792b394a5a6cda10cc358ba58436fe29/ShortcutBadger/src/main/AndroidManifest.xml

**Comment by Tembac** [comment]
Hi Sam!

Thanks for the extension and your help.

This is strange because that is were I first searched for the permissions but I tried deleting all from the manifests and the permissions are still required. Maybe there are on other place? Maybe they are mandatory for this?

**Comment by Tw1ddle** [comment]
Did you do a clean rebuild, and what Android version and phone model do you use? I will try to repro the issue with my demo app at somepoint, this weekend if I have time: https://github.com/Tw1ddle/samcodes-notifications-demo

**Comment by Tembac** [comment]
Thanks!
Yes. I did clean rebuilds at every change. I'm using a samsung galaxy S5 with android 6.0.1 to test and also an emulator of pixel 2 xl with android 9.

I'l try your demo.

**Comment by Tembac** [comment]
Thanks!

Yes, I'm doing clean builds. I'm testing on a samsung galaxy s5 with android 6 and an emulator of pixel xl2 with android 9.

Your demo is giving me a failure when I try to build:
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':deps:google-play-services:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Development\androidSDK\build-tools\28.0.3\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by Tw1ddle** [comment]
Hi, I repro'd the issue and think I've fixed it with this: https://github.com/Tw1ddle/samcodes-notifications/commit/19f13797c807f6f5655daf0581d92bb967873846 - let me know if my reasoning checks out and we can close this.

Also, the demo will hopefully build again, I made several updates to the haxelib and demo today.

I believe the issue was due to the manifest merger inferring permissions. I needed to properly specify a minimum/target Android SDK version in build.gradle for this haxelib, which we weren't doing before - the manifest-merger-debug-report.txt in the Android export folder contained this:

> android:uses-permission#android.permission.WRITE_EXTERNAL_STORAGE
> IMPLIED from C:\Code\HaxeCoding\samcodes-notifications-demo\export\android\bin\app\src\main\AndroidManifest.xml:2:1-31:12 reason: com.samcodes.notifications has a targetSdkVersion < 4

> android:uses-permission#android.permission.READ_PHONE_STATE
> IMPLIED from C:\Code\HaxeCoding\samcodes-notifications-demo\export\android\bin\app\src\main\AndroidManifest.xml:2:1-31:12 reason: com.samcodes.notifications has a targetSdkVersion < 4

> android:uses-permission#android.permission.READ_EXTERNAL_STORAGE
> IMPLIED from C:\Code\HaxeCoding\samcodes-notifications-demo\export\android\bin\app\src\main\AndroidManifest.xml:2:1-31:12 reason: com.samcodes.notifications requested WRITE_EXTERNAL_STORAGE

These are obviously the unwanted Phone and Storage permissions :smile:

**Comment by Tembac** [comment]
Thanks a lot!

It works great now and it is not asking for permissions. I can also compile the demo fine now.
